from datetime import timedelta

DOMAIN = "prayer_times_morocco"
CONF_CITY = "city"
CONF_LANGUAGE = "language"

UPDATE_INTERVAL = timedelta(hours=1)

PRAYERS = ["fajr", "chourouk", "dohr", "asr", "maghrib", "ichaa"]
LANGUAGES = ["english", "arabic"]

PRAYERS_NAMES = {
    "english": {
        "fajr": "Fajr",
        "chourouk": "Sunrise",
        "dohr": "Dhuhr",
        "asr": "Asr",
        "maghrib": "Maghrib",
        "ichaa": "Isha",
        "next": "Next Prayer",
        "next_time": "Next Prayer Time",
        "date": "Date",
        "city": "City"
    },
    "arabic": {
        "fajr": "الفجر",
        "chourouk": "الشروق",
        "dohr": "الظهر",
        "asr": "العصر",
        "maghrib": "المغرب",
        "ichaa": "العشاء",
        "next": "الصلاة القادمة",
        "next_time": "وقت الصلاة القادمة",
        "date": "التاريخ",
        "city": "المدينة"
    }
}

CITIES_MAP = {
  "Agadir": 117,
  "Al Hoceima": 23,
  "Aousserd": 167,
  "Assa-Zag": 150,
  "Azilal": 74,
  "Beni Mellal": 73,
  "Benslimane": 60,
  "Berkane": 32,
  "Berrechid": 65,
  "Boujdour": 158,
  "Boulemane": 84,
  "Casablanca": 58,
  "Chefchaouen": 18,
  "Chichaoua": 107,
  "Dakhla": 165,
  "El Hajeb": 101,
  "El Jadida": 66,
  "El Kelaa des Sraghna": 105,
  "Errachidia": 128,
  "Es-Semara": 157,
  "Essaouira": 106,
  "Fes": 81,
  "Figuig": 33,
  "Fquih Ben Salah": 75,
  "Guelmim": 149,
  "Guercif": 35,
  "Ifrane": 100,
  "Inezgane-Ait Melloul": 117,
  "Jerada": 36,
  "Kenitra": 7,
  "Khemisset": 2,
  "Khenifra": 70,
  "Khouribga": 79,
  "L'Oriental": 31,
  "Laayoune": 156,
  "Larache": 16,
  "Marrakech": 104,
  "Mechraâ Bel Ksiri": 8,
  "Mediouna": 58,
  "Meknes": 99,
  "Midelt": 136,
  "Mohammadia": 59,
  "Moulay Yacoub": 83,
  "Nador": 39,
  "Nouaceur": 58,
  "Ouarzazate": 138,
  "Ouezzane": 29,
  "Oujda": 31,
  "Rabat": 1,
  "Rehamna": 109,
  "Safi": 111,
  "Sale": 1,
  "Sefrou": 82,
  "Settat": 61,
  "Sidi Bennour": 68,
  "Sidi Ifni": 148,
  "Sidi Kacem": 8,
  "Sidi Slimane": 10,
  "Skhirate-Temara": 1,
  "Tan-Tan": 152,
  "Tanger": 14,
  "Taounate": 90,
  "Taourirt": 38,
  "Tarfaya": 159,
  "Taroudannt": 118,
  "Tata": 123,
  "Taza": 89,
  "Tetouan": 15,
  "Tiznit": 119,
  "Youssoufia": 113,
  "Zagora": 137
}

CITY_TRANSLATIONS = {
  "Agadir": "أكادير",
  "Al Hoceima": "الحسيمة",
  "Aousserd": "أوسرد",
  "Assa-Zag": "آسا الزاك",
  "Azilal": "أزيلال",
  "Beni Mellal": "بني ملال",
  "Benslimane": "بنسليمان",
  "Berkane": "بركان",
  "Berrechid": "برشيد",
  "Boujdour": "بوجدور",
  "Boulemane": "بولمان",
  "Casablanca": "الدار البيضاء",
  "Chefchaouen": "شفشاون",
  "Chichaoua": "شيشاوة",
  "Dakhla": "الداخلة",
  "El Hajeb": "الحاجب",
  "El Jadida": "الجديدة",
  "El Kelaa des Sraghna": "قلعة السراغنة",
  "Errachidia": "الرشيدية",
  "Es-Semara": "السمارة",
  "Essaouira": "الصويرة",
  "Fes": "فاس",
  "Figuig": "فكيك",
  "Fquih Ben Salah": "الفقيه بن صالح",
  "Guelmim": "كلميم",
  "Guercif": "جرسيف",
  "Ifrane": "إفران",
  "Inezgane-Ait Melloul": "إنزكان آيت ملول",
  "Jerada": "جرادة",
  "Kenitra": "القنيطرة",
  "Khemisset": "الخميسات",
  "Khenifra": "خنيفرة",
  "Khouribga": "خريبكة",
  "L'Oriental": "الشرق",
  "Laayoune": "العيون",
  "Larache": "العرائش",
  "Marrakech": "مراكش",
  "Mechraâ Bel Ksiri": "مشرع بلقصيري",
  "Mediouna": "مديونة",
  "Meknes": "مكناس",
  "Midelt": "ميدلت",
  "Mohammadia": "المحمدية",
  "Moulay Yacoub": "مولاي يعقوب",
  "Nador": "الناظور",
  "Nouaceur": "النواصر",
  "Ouarzazate": "ورزازات",
  "Ouezzane": "وزان",
  "Oujda": "وجدة",
  "Rabat": "الرباط",
  "Rehamna": "الرحامنة",
  "Safi": "آسفي",
  "Sale": "سلا",
  "Sefrou": "صفرو",
  "Settat": "سطات",
  "Sidi Bennour": "سيدي بنور",
  "Sidi Ifni": "سيدي إفني",
  "Sidi Kacem": "سيدي قاسم",
  "Sidi Slimane": "سيدي سليمان",
  "Skhirate-Temara": "الصخيرات تمارة",
  "Tan-Tan": "طانطان",
  "Tanger": "طنجة",
  "Taounate": "تاونات",
  "Taourirt": "تاوريرت",
  "Tarfaya": "طرفاية",
  "Taroudannt": "تارودانت",
  "Tata": "طاطا",
  "Taza": "تازة",
  "Tetouan": "تطوان",
  "Tiznit": "تيزنيت",
  "Youssoufia": "اليوسفية",
  "Zagora": "زاكورة"
}
